- name: Unarchive etcd package
  unarchive:
    src: "/opt/etcd-v{{etcdVersion}}-linux-amd64.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts:
     - --strip-components=1
    exclude:
     - "*.md"
     - "Document"
  tags: unarchive_etcd_package
