- name: daemon-reload
  systemd: daemon_reload=yes
  tags: kube-proxy_start 

- name: init service kube-proxy
  service:
    name: kube-proxy
    enabled: yes 
    state: started
  tags: kube-proxy_start
