- name: contained config 1
  copy: src=containerd.conf dest=/etc/modules-load.d/ owner=root group=root mode=0644
  tags: contained_config

- name: contained config 2
  shell: modprobe -- overlay && modprobe -- br_netfilter
  tags: contained_config

- name: contained config 3
  copy: src=99-kuberneters-cri.conf dest=/etc/sysctl.d/ owner=root group=root mode=0644 
  tags: contained_config

- name: contained config 4
  shell: sysctl --system    
  tags: contained_config

- name: contained config 5
  shell: containerd config default > /etc/containerd/config.toml
  tags: contained_config

- name: contained config 6
  shell: sed -e 's|SystemdCgroup = false|SystemdCgroup = true|g' -e 's|k8s.gcr.io/pause:3.6|registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6|g' -i.bak /etc/containerd/config.toml
  tags: contained_config
