- name: daemon-reload
  systemd: daemon_reload=yes
  tags: kube-apiserver_start 

- name: init service kube-apiserver 
  service:
    name: kube-apiserver
    enabled: yes 
    state: started
  tags: kube-apiserver_start
