- name: install package 1
  dnf:
    name:
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
  tags: repo


- name: install package 2
  shell: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  tags: repo

- name: install package 3
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644
  tags: repo
