- name: stop system service 
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
#  loop: [firewalld,dnsmasq,NetworkManager]
  loop: [firewalld,dnsmasq]
  ignore_errors: yes
  tags: service
