- name: stop selinux 
  shell: setenforce 0 && sed -i 's#SELINUX=enforcing#SELINUX=disabled#g' /etc/sysconfig/selinux && sed -i 's#SELINUX=enforcing#SELINUX=disabled#g' /etc/selinux/config 
  ignore_errors: yes
  tags: stop_selinux 
